site_name: Syed's Home
theme:
  name: material
  features:
    - navigation.tabs
    - content.tabs.link
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - content.code.copy

plugins:
  - glightbox
  - search

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - About me: index.md
  - Academia: 
    - Teaching: ./academia/teaching.md
    - Supervision : ./academia/supervision.md
    - PhD Examination: ./academia/phd_examination.md
    - Admin Roles: ./academia/admin.md
    - Affiliations: ./academia/affiliations.md
    - Academic CV: ./academia/cv.md
  - Publications: publication.md
  - Research :
    - Research Interest : ./research/research_interest.md
    - Program Analysis Projects : ./research/program-analysis.md
    - Cloud Security Projects : ./research/cloud-security.md
    - SBSE Projects: ./research/fastfix.md
    - Visualization Projects: ./research/visualization.md
    - Project Ideas for Students : ./research/project_ideas.md
  - Awards : 
    - Awards & Achievements : ./awards/awards.md
    - UEL Awards Event : ./awards/event-videos-photo.md
    - Badges : ./awards/badges.md
  - Study Notes :
    - AWS Practitioner :
       - Introduction : ./notes/aws-practitioner/introduction.md
       - Domains : ./notes/aws-practitioner/domains.md
       - Computing : ./notes/aws-practitioner/compute.md
       - Storage : ./notes/aws-practitioner/storage.md
       - Database: ./notes/aws-practitioner/database.md
       - Networking: ./notes/aws-practitioner/networking.md
       - Other Services: ./notes/aws-practitioner/other-services.md
       - Queuing Service: ./notes/aws-practitioner/queuing-service.md
       - Streaming : ./notes/aws-practitioner/streaming.md
       - Security and Compliance : ./notes/aws-practitioner/security-compliance.md
       - Disaster Recovery : ./notes/aws-practitioner/disaster-recovery.md
       - Management : ./notes/aws-practitioner/management.md
    - AWS Developer Associate :
       - Introduction : ./notes/aws-dva/introduction.md
       
    
  
